
package usuarios;

import Metodos_sql.Metodos_sql;
import iniciosesion.Login;
import acercade.nosotros;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


public class Bienvenido extends javax.swing.JFrame {

    

    public Bienvenido() {
        initComponents();
        this.setLocationRelativeTo(this);
        getContentPane().setBackground(Color.ORANGE);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        
    }
    
Metodos_sql metodos = new Metodos_sql();
   String user;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnReserva = new javax.swing.JButton();
        btnCartilla = new javax.swing.JButton();
        btnMenuDelDia = new javax.swing.JButton();
        btnMasConsumidos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPromos1 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        btnacercade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO");

        btnReserva.setBackground(new java.awt.Color(204, 255, 204));
        btnReserva.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnReserva.setText("Realizar Reserva");
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });

        btnCartilla.setBackground(new java.awt.Color(153, 255, 153));
        btnCartilla.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCartilla.setText("Cartilla");
        btnCartilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartillaActionPerformed(evt);
            }
        });

        btnMenuDelDia.setBackground(new java.awt.Color(102, 255, 102));
        btnMenuDelDia.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnMenuDelDia.setText("Menu del Dia");
        btnMenuDelDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuDelDiaActionPerformed(evt);
            }
        });

        btnMasConsumidos.setBackground(new java.awt.Color(51, 204, 0));
        btnMasConsumidos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnMasConsumidos.setText("Más Consumidos");
        btnMasConsumidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasConsumidosActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPromos1.setBackground(new java.awt.Color(51, 255, 51));
        btnPromos1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnPromos1.setText("Promos");
        btnPromos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromos1ActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N

        btnacercade.setBackground(new java.awt.Color(255, 102, 102));
        btnacercade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnacercade.setText("Acerca De");
        btnacercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacercadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 156, Short.MAX_VALUE)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCartilla, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(btnReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(btnMenuDelDia, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(btnPromos1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(btnMasConsumidos, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnacercade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCartilla, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnMenuDelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPromos1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMasConsumidos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnacercade))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        // TODO add your handling code here:
            user = Login.user;
            
            //captura el nombre
            String busqueda_nombre = metodos.buscarNombre(user);
            
            //caputura id
             int  busqueda_id = metodos.buscarId(user);
             String buscarid = String.valueOf(busqueda_id);
            
            Reserva re = new Reserva();
            re.jLabelnombre.setText(busqueda_nombre);
            re.jLabelid.setText(buscarid);
            
            re.setVisible(true);
            //this.dispose();
        
       
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnCartillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartillaActionPerformed
        // TODO add your handling code here:
        Cartilla ca = new Cartilla();
        ca.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnCartillaActionPerformed

    private void btnMenuDelDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDelDiaActionPerformed
        // TODO add your handling code here:
         MenuDelDia me = new MenuDelDia();
        me.setVisible(true);
          
      
//        this.dispose();
    }//GEN-LAST:event_btnMenuDelDiaActionPerformed

    private void btnMasConsumidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasConsumidosActionPerformed
        // TODO add your handling code here:
        MasConsumidos ms = new   MasConsumidos();
        ms.setVisible(true);
       
    }//GEN-LAST:event_btnMasConsumidosActionPerformed

    private void btnPromos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromos1ActionPerformed
        // TODO add your handling code here:
          Promos pr = new Promos();
         pr.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnPromos1ActionPerformed

    private void btnacercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacercadeActionPerformed
        // TODO add your handling code here:ç
        
        nosotros ac = new nosotros();
        ac.setVisible(true);
//        this.dispose();
        
    }//GEN-LAST:event_btnacercadeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
       Login l = new Login();
       l.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCartilla;
    private javax.swing.JButton btnMasConsumidos;
    private javax.swing.JButton btnMenuDelDia;
    private javax.swing.JButton btnPromos1;
    public javax.swing.JButton btnReserva;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnacercade;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

@Override
    public Image getIconImage(){
    
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("/imagenes/icono.png"));
        return retValue;
    }    

}
