
package usuarios;

import Metodos_sql.ConexionBD;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;


public class Mesas extends javax.swing.JFrame {


    public Mesas() {
        initComponents();
        this.setLocationRelativeTo(this);
        botones();
        buscarMesasReservadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        Horario = new javax.swing.JComboBox<>();
        pnlBotones = new javax.swing.JPanel();
        Dias = new javax.swing.JComboBox<>();
        Meses = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MESAS");

        btnConfirmar.setText("Confirmar");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        Horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11:00", "12:00", "13:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        Dias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Meses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel2.setText("Día");

        jLabel3.setText("Mes");

        jLabel4.setText("Hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Meses, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(165, 165, 165)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnVolver))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Reserva re = new Reserva();
        re.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btnVolverActionPerformed

    //conectar con la base de datos 
   ConexionBD cc= new ConexionBD();
   Connection con=cc.conectar();
   
   int filas = 3;
   int columnas = 3;
   int largoBoton = 95;
   int anchoBoton = 95;
   int ejex = 20;
   int ejey = 20;
   
   public JToggleButton [][] JTBotones = new JToggleButton[filas][columnas];
   
   //public static Connection conexion;
   public static PreparedStatement sentenciaPreparada;
   public static ResultSet resultado;
    
   
    //METODO PARA EL DISEÑO DE LOS BOTONES
   public void botones(){
       Font fuenteLetra = new Font("Arial",Font.BOLD,12);
       int contadorMesas = 1;
       JTBotones = new JToggleButton[filas][columnas];
       for (int i = 0; i < filas; i++) {
           for (int j = 0; j < columnas; j++) {
               JTBotones[i][j] = new JToggleButton();
               JTBotones[i][j].setBounds(ejex, ejey, largoBoton, anchoBoton);
               JTBotones[i][j].setText("Mesa " + contadorMesas);
               JTBotones[i][j].setFont(fuenteLetra);
               JTBotones[i][j].setBackground(new Color(38, 197, 43));
               
               AccionBotones accion = new AccionBotones();
               JTBotones[i][j].addActionListener(accion);
               
               pnlBotones.add(JTBotones[i][j]);
               
               contadorMesas++;
               ejex += 130;
           }
           ejex = 20; // posicion inicial
           ejey += 100; // separacion de los btn
       }
   }
   
   //METODO PARA RESERVAR MESA
    public void reservarMesa(int numero){
	try{
		con = ConexionBD.conectar();
		String consulta = "UPDATE mesas SET reservado = 'si' WHERE numero = " + numero;
		sentenciaPreparada = con.prepareStatement(consulta);
		int mensaje = sentenciaPreparada.executeUpdate();
		
		if(mensaje > 0){
			JOptionPane.showMessageDialog(null, "Mesa reservada");
		} else JOptionPane.showMessageDialog(null, "Error al actualizar el estado de la Mesa");
	}catch (Exception e){
		System.out.println("Error: " + e);
	}
}

    //METODO PARA QUITAR MESA
    public void quitarMesa(int numero){
	try{
		con = ConexionBD.conectar();
		String consulta = "UPDATE mesas SET reservado = 'no' WHERE numero = "+ numero;
		sentenciaPreparada = con.prepareStatement(consulta);
		int mensaje = sentenciaPreparada.executeUpdate();
		
		if(mensaje > 0){
			JOptionPane.showMessageDialog(null, "Se ha liberado la Mesa");
		} else JOptionPane.showMessageDialog(null, "Error al actualizar el estado de la Mesa");
	}catch (Exception e){
		System.out.println("Error: " + e);
	}
}
    
    //METODO PARA BUSCAR MESAS RESERVADAS
    public void buscarMesasReservadas(){
        
        try {
            con = ConexionBD.conectar();
            String consulta = "SELECT numero, reservado FROM mesas";
            sentenciaPreparada = con.prepareStatement(consulta);
            resultado = sentenciaPreparada.executeQuery();
            int numero;
            String reservado;
            
            while(resultado.next()){
                numero = resultado.getInt("numero");
                reservado = resultado.getString("reservado");
                
                for (int i = 0; i < filas; i++) {
                    for (int j = 0; j < columnas; j++) {
                        
                        if (JTBotones[i][j].getText().length() == 6) {
                            String numeroLetra = JTBotones[i][j].getText().charAt(5)+"";
                            int numeroN = Integer.parseInt(numeroLetra);
                            if ((numero == numeroN)&&(reservado.equals("si"))) {
                                JTBotones[i][j].setBackground(Color.RED);
                                JTBotones[i][j].setSelected(true);
                            }
                        }
                    }
                }
            }
            
        } catch (SQLException e) {
            System.out.println("Error: " + e);
        }
    }
    
    public class AccionBotones implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < columnas; j++) {
                    if (ae.getSource().equals(JTBotones[i][j])) {
                        if (JTBotones[i][j].isSelected()) {
                            JTBotones[i][j].setBackground(Color.RED);
                            if (JTBotones[i][j].getText().length() == 6) {
                                String numeroLetra = JTBotones[i][j].getText().charAt(5)+"";
                                int numero = Integer.parseInt(numeroLetra);
                                reservarMesa(numero);
                            }
                        }else{
                            JTBotones[i][j].setBackground(new Color(38, 197, 43));
                            if (JTBotones[i][j].getText().length() == 6) {
                                String numeroLetra = JTBotones[i][j].getText().charAt(5)+"";
                                int numero = Integer.parseInt(numeroLetra);
                                quitarMesa(numero);
                            }
                        }
                    }
                }
            }
            
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Dias;
    private javax.swing.JComboBox<String> Horario;
    private javax.swing.JComboBox<String> Meses;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
